image: jangrewe/gitlab-ci-android

variables:
  VERSION_SDK_TOOLS: "24.4.1"
  VERSION_BUILD_TOOLS: "24.0.0"
  VERSION_TARGET_SDK: "24"

before_script:
  - chmod +x gradlew

stages:
  - build

debug:
  stage: build
  except:
    - release
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/app-debug.apk
